---
Name: silverstripe-terms-and-conditions
---
#See https://docs.silverstripe.org/en/4/developer_guides/files/file_management/
SilverStripe\Assets\File:
  keep_archived_assets: true


SilverStripe\Security\Member:
  extensions:
    - Suilven\TermsAndConditions\Model\MemberTOCSignatureExtension

SilverStripe\Forms\Form:
  extensions:
    - Suilven\TermsAndConditions\Extension\FormTOCProtectionExtension
